In [1]:
import pandas as pd

## Alzheimers

In [2]:
alzheimers_male = pd.read_csv('full_panel_condition_alz_male.csv')
alzheimers_male = alzheimers_male.loc[:, ~alzheimers_male.columns.str.contains('^Unnamed')]

In [3]:
alzheimers_male.head()

,Run ID,Sex,Age,Country,Condition,Abiotrophia,Acanthopleuribacter,Acholeplasma,Acidaminococcus,Acinetobacter,...,Thermoanaerobacter,Truepera,Tyzzerella,Uliginosibacterium,Unknown,Veillonella,Victivallis,Virgibacillus,Weissella,Yersinia
0,ERR1090510,Male,31,United States of America,Alzheimers,0.0,0.008079,0.000000,0.937222,0.016159,...,0.000000,0.000000,0.339339,0.032318,18.9626,0.000000,0.000000,0.000000,0.0,0.000000
1,ERR1843463,Male,70,United States of America,"Alzheimers, Autoimmune Diseases",0.0,0.000000,0.000000,0.036957,0.000000,...,0.000000,0.000000,0.000000,0.000000,42.9544,0.026398,0.042236,0.015839,0.0,0.000000
2,ERR1844528,Male,70,United States of America,"Alzheimers, Autoimmune Diseases",0.0,0.000000,0.000000,0.027337,0.005467,...,0.000000,0.005467,0.000000,0.000000,42.1542,0.049207,0.027337,0.000000,0.0,0.005467
3,ERR2091834,Male,56,United Kingdom,Alzheimers,0.0,0.000000,0.078935,0.036836,0.000000,...,0.010525,0.000000,0.005262,0.000000,11.7560,0.000000,0.000000,0.000000,0.0,0.000000
4,SRR9671458,Male,64,China,Alzheimers,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,183.0010,0.000000,0.000000,0.000000,0.0,0.000000

In [4]:
alzheimers_male['Condition'] = 1
alzheimers_male.rename(columns={'Condition': 'Is Alzheimers?'}, inplace=True)

In [5]:
alzheimers_male.head()

,Run ID,Sex,Age,Country,Is Alzheimers?,Abiotrophia,Acanthopleuribacter,Acholeplasma,Acidaminococcus,Acinetobacter,...,Thermoanaerobacter,Truepera,Tyzzerella,Uliginosibacterium,Unknown,Veillonella,Victivallis,Virgibacillus,Weissella,Yersinia
0,ERR1090510,Male,31,United States of America,1,0.0,0.008079,0.000000,0.937222,0.016159,...,0.000000,0.000000,0.339339,0.032318,18.9626,0.000000,0.000000,0.000000,0.0,0.000000
1,ERR1843463,Male,70,United States of America,1,0.0,0.000000,0.000000,0.036957,0.000000,...,0.000000,0.000000,0.000000,0.000000,42.9544,0.026398,0.042236,0.015839,0.0,0.000000
2,ERR1844528,Male,70,United States of America,1,0.0,0.000000,0.000000,0.027337,0.005467,...,0.000000,0.005467,0.000000,0.000000,42.1542,0.049207,0.027337,0.000000,0.0,0.005467
3,ERR2091834,Male,56,United Kingdom,1,0.0,0.000000,0.078935,0.036836,0.000000,...,0.010525,0.000000,0.005262,0.000000,11.7560,0.000000,0.000000,0.000000,0.0,0.000000
4,SRR9671458,Male,64,China,1,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,183.0010,0.000000,0.000000,0.000000,0.0,0.000000

In [6]:
alzheimers_female = pd.read_csv('full_panel_condition_alz_female.csv')
alzheimers_female = alzheimers_female.loc[:, ~alzheimers_female.columns.str.contains('^Unnamed')]

In [7]:
alzheimers_female.head()

,Run ID,Sex,Age,Country,Condition,Acetobacterium,Acholeplasma,Acidaminococcus,Acidihalobacter,Acidithiobacillus,...,Treponema,Tyzzerella,Unknown,Varibaculum,Veillonella,Verrucomicrobium,Vibrio,Victivallis,Viridibacillus,Weissella
0,ERR1160800,Female,53,United States of America,"Alzheimers, Migrane Disorders",0.001165,0.009320,0.33086,0.001165,0.003495,...,0.0,0.001165,40.5105,0.00932,1.00889,0.005825,0.08854,0.00233,0.001165,0.00233
1,ERR2091942,Female,53,United Kingdom,"Alzheimers, Intestinal Diseases",0.000000,0.946936,0.00000,0.000000,0.000000,...,0.0,0.003573,35.6012,0.00000,0.00000,0.000000,0.00000,0.00000,0.000000,0.00000
2,SRR9671487,Female,67,China,Alzheimers,0.000000,0.000000,0.00000,0.000000,0.000000,...,0.0,0.000000,170.0640,0.00000,0.00000,0.000000,0.00000,0.00000,0.000000,0.00000
3,SRR9671488,Female,80,China,Alzheimers,0.000000,0.000000,0.00000,0.000000,0.000000,...,0.0,0.000000,114.2700,0.00000,0.00000,0.000000,0.00000,0.00000,0.000000,0.00000
4,SRR9671489,Female,57,China,Alzheimers,0.000000,0.000000,0.00000,0.000000,0.000000,...,0.0,0.000000,91.3630,0.00000,0.00000,0.000000,0.00000,0.00000,0.000000,0.00000

In [8]:
alzheimers_female['Condition'] = 1
alzheimers_female.rename(columns={'Condition': 'Is Alzheimers?'}, inplace=True)

In [9]:
alzheimers_female.head()

,Run ID,Sex,Age,Country,Is Alzheimers?,Acetobacterium,Acholeplasma,Acidaminococcus,Acidihalobacter,Acidithiobacillus,...,Treponema,Tyzzerella,Unknown,Varibaculum,Veillonella,Verrucomicrobium,Vibrio,Victivallis,Viridibacillus,Weissella
0,ERR1160800,Female,53,United States of America,1,0.001165,0.009320,0.33086,0.001165,0.003495,...,0.0,0.001165,40.5105,0.00932,1.00889,0.005825,0.08854,0.00233,0.001165,0.00233
1,ERR2091942,Female,53,United Kingdom,1,0.000000,0.946936,0.00000,0.000000,0.000000,...,0.0,0.003573,35.6012,0.00000,0.00000,0.000000,0.00000,0.00000,0.000000,0.00000
2,SRR9671487,Female,67,China,1,0.000000,0.000000,0.00000,0.000000,0.000000,...,0.0,0.000000,170.0640,0.00000,0.00000,0.000000,0.00000,0.00000,0.000000,0.00000
3,SRR9671488,Female,80,China,1,0.000000,0.000000,0.00000,0.000000,0.000000,...,0.0,0.000000,114.2700,0.00000,0.00000,0.000000,0.00000,0.00000,0.000000,0.00000
4,SRR9671489,Female,57,China,1,0.000000,0.000000,0.00000,0.000000,0.000000,...,0.0,0.000000,91.3630,0.00000,0.00000,0.000000,0.00000,0.00000,0.000000,0.00000

In [10]:
healthy_male = pd.read_csv('full_panel_condition_healthy_male.csv')
healthy_male = healthy_male.loc[:, ~healthy_male.columns.str.contains('^Unnamed')]

In [11]:
healthy_male.head()

,Run ID,Sex,Age,Country,Condition,BMI,Abiotrophia,Acetivibrio,Acetoanaerobium,Acetobacter,...,unclassified Clostridiales (miscellaneous),unclassified Clostridiales Family XIII. Incertae Sedis,unclassified Coriobacteriaceae,unclassified Erysipelotrichaceae (miscellaneous),unclassified Lachnospiraceae,unclassified Peptostreptococcaceae,unclassified Peptostreptococcaceae (miscellaneous),unclassified Propionibacteriaceae,unclassified Sutterellaceae,unclassified Tissierellia
0,ERR1075960,Male,0.0,United States of America,Health,21.22,0.000000,0.003877,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0000,0.0,0.0,0.0,0.0000,0.0
1,ERR1854747,Male,62.0,United Kingdom,Health,28.70,0.000000,0.000000,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0000,0.0,0.0,0.0,0.0000,0.0
2,ERR688529,Male,63.0,Austria,Health,30.90,0.000000,0.000000,0.0,0.0,...,0.00926,0.0,0.0,0.02919,2.3641,0.0,0.0,0.0,0.0144,0.0
3,ERR1316059,Male,67.0,United States of America,Health,22.15,0.000000,0.000000,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0000,0.0,0.0,0.0,0.0000,0.0
4,SRR5649200,Male,27.0,United States of America,Health,20.80,0.001814,0.000000,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0000,0.0,0.0,0.0,0.0000,0.0

In [12]:
healthy_male['Condition'] = 0
healthy_male.rename(columns={'Condition': 'Is Alzheimers?'}, inplace=True)

In [13]:
healthy_male.head()

,Run ID,Sex,Age,Country,Is Alzheimers?,BMI,Abiotrophia,Acetivibrio,Acetoanaerobium,Acetobacter,...,unclassified Clostridiales (miscellaneous),unclassified Clostridiales Family XIII. Incertae Sedis,unclassified Coriobacteriaceae,unclassified Erysipelotrichaceae (miscellaneous),unclassified Lachnospiraceae,unclassified Peptostreptococcaceae,unclassified Peptostreptococcaceae (miscellaneous),unclassified Propionibacteriaceae,unclassified Sutterellaceae,unclassified Tissierellia
0,ERR1075960,Male,0.0,United States of America,0,21.22,0.000000,0.003877,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0000,0.0,0.0,0.0,0.0000,0.0
1,ERR1854747,Male,62.0,United Kingdom,0,28.70,0.000000,0.000000,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0000,0.0,0.0,0.0,0.0000,0.0
2,ERR688529,Male,63.0,Austria,0,30.90,0.000000,0.000000,0.0,0.0,...,0.00926,0.0,0.0,0.02919,2.3641,0.0,0.0,0.0,0.0144,0.0
3,ERR1316059,Male,67.0,United States of America,0,22.15,0.000000,0.000000,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0000,0.0,0.0,0.0,0.0000,0.0
4,SRR5649200,Male,27.0,United States of America,0,20.80,0.001814,0.000000,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0000,0.0,0.0,0.0,0.0000,0.0

In [14]:
healthy_female = pd.read_csv('full_panel_condition_healthy_female.csv')
healthy_female = healthy_female.loc[:, ~healthy_female.columns.str.contains('^Unnamed')]

In [15]:
healthy_female.head()

,Run ID,Sex,Age,Country,Condition,BMI,Abiotrophia,Acanthopleuribacter,Acaryochloris,Acetoanaerobium,...,unclassified Clostridiales Family XIII. Incertae Sedis,unclassified Dermatophilaceae,unclassified Erysipelotrichaceae,unclassified Erysipelotrichaceae (miscellaneous),unclassified Lachnospiraceae,unclassified Peptostreptococcaceae,unclassified Peptostreptococcaceae (miscellaneous),unclassified Propionibacteriaceae,unclassified Ruminococcaceae,unclassified Sutterellaceae
0,ERR1842901,Female,63.0,United Kingdom,Health,21.0300,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,ERR719035,Female,26.0,Canada,Health,19.0311,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,SRR5648781,Female,21.0,United States of America,Health,20.0000,0.001134,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ERR2032350,Female,24.0,United States of America,Health,24.1300,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,ERR1089968,Female,63.0,United States of America,Health,24.6300,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
healthy_female['Condition'] = 0
healthy_female.rename(columns={'Condition': 'Is Alzheimers?'}, inplace=True)

In [17]:
healthy_female.head()

,Run ID,Sex,Age,Country,Is Alzheimers?,BMI,Abiotrophia,Acanthopleuribacter,Acaryochloris,Acetoanaerobium,...,unclassified Clostridiales Family XIII. Incertae Sedis,unclassified Dermatophilaceae,unclassified Erysipelotrichaceae,unclassified Erysipelotrichaceae (miscellaneous),unclassified Lachnospiraceae,unclassified Peptostreptococcaceae,unclassified Peptostreptococcaceae (miscellaneous),unclassified Propionibacteriaceae,unclassified Ruminococcaceae,unclassified Sutterellaceae
0,ERR1842901,Female,63.0,United Kingdom,0,21.0300,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,ERR719035,Female,26.0,Canada,0,19.0311,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,SRR5648781,Female,21.0,United States of America,0,20.0000,0.001134,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ERR2032350,Female,24.0,United States of America,0,24.1300,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,ERR1089968,Female,63.0,United States of America,0,24.6300,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
is_alz_df = pd.concat([alzheimers_male, alzheimers_female, healthy_male, healthy_female])

In [19]:
is_alz_df = is_alz_df.fillna(0)

In [20]:
is_alz_df.head()

,Run ID,Sex,Age,Country,Is Alzheimers?,Abiotrophia,Acanthopleuribacter,Acholeplasma,Acidaminococcus,Acinetobacter,...,Weeksella,Wigglesworthia,Wolbachia,Zooshikella,unclassified Bacteroidetes (miscellaneous),unclassified Clostridiaceae,unclassified Clostridiales,unclassified Dermatophilaceae,unclassified Erysipelotrichaceae,unclassified Ruminococcaceae
0,ERR1090510,Male,31.0,United States of America,1,0.0,0.008079,0.000000,0.937222,0.016159,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,ERR1843463,Male,70.0,United States of America,1,0.0,0.000000,0.000000,0.036957,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,ERR1844528,Male,70.0,United States of America,1,0.0,0.000000,0.000000,0.027337,0.005467,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ERR2091834,Male,56.0,United Kingdom,1,0.0,0.000000,0.078935,0.036836,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,SRR9671458,Male,64.0,China,1,0.0,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
is_alz_df.to_csv('alzheimers_healthy_for_pca_one_condition.csv')

## Parkinsons

In [22]:
parkinsons_male = pd.read_csv('full_panel_condition_park_male.csv')
parkinsons_male = parkinsons_male.loc[:, ~parkinsons_male.columns.str.contains('^Unnamed')]

In [23]:
parkinsons_male.head()

,Run ID,Sex,Age,Country,Condition,Acidaminococcus,Adlercreutzia,Aggregatibacter,Akkermansia,Alistipes,...,Shewanella,Streptococcus,Subdoligranulum,Succinivibrio,Sutterella,Turicibacter,Unknown,Veillonella,Vibrio,Victivallis
0,ERR365909,Male,61,Finland,Parkinsons,0.00000,0.0,0.0,0.0,0.429130,...,0.0,0.000000,6.10880,0.0,0.000000,0.00000,90.3698,0.000000,0.0,0.0
1,ERR365910,Male,53,Finland,Parkinsons,0.00000,0.0,0.0,0.0,0.489687,...,0.0,0.000000,4.34783,0.0,0.830984,0.14839,109.3040,0.192907,0.0,0.0
2,ERR365912,Male,66,Finland,Parkinsons,3.34422,0.0,0.0,0.0,1.345530,...,0.0,0.052253,10.52910,0.0,2.259960,0.07838,21.5545,0.000000,0.0,0.0
3,ERR365914,Male,63,Finland,Parkinsons,0.00000,0.0,0.0,0.0,0.191301,...,0.0,0.000000,4.19855,0.0,2.486910,0.00000,111.7200,0.000000,0.0,0.0
4,ERR365915,Male,72,Finland,Parkinsons,3.72852,0.0,0.0,0.0,0.718898,...,0.0,0.146217,1.63275,0.0,1.657120,0.00000,49.4212,0.085293,0.0,0.0

In [24]:
parkinsons_male['Condition'] = 1
parkinsons_male.rename(columns={'Condition': 'Is Parkinsons?'}, inplace=True)

In [25]:
parkinsons_male.head()

,Run ID,Sex,Age,Country,Is Parkinsons?,Acidaminococcus,Adlercreutzia,Aggregatibacter,Akkermansia,Alistipes,...,Shewanella,Streptococcus,Subdoligranulum,Succinivibrio,Sutterella,Turicibacter,Unknown,Veillonella,Vibrio,Victivallis
0,ERR365909,Male,61,Finland,1,0.00000,0.0,0.0,0.0,0.429130,...,0.0,0.000000,6.10880,0.0,0.000000,0.00000,90.3698,0.000000,0.0,0.0
1,ERR365910,Male,53,Finland,1,0.00000,0.0,0.0,0.0,0.489687,...,0.0,0.000000,4.34783,0.0,0.830984,0.14839,109.3040,0.192907,0.0,0.0
2,ERR365912,Male,66,Finland,1,3.34422,0.0,0.0,0.0,1.345530,...,0.0,0.052253,10.52910,0.0,2.259960,0.07838,21.5545,0.000000,0.0,0.0
3,ERR365914,Male,63,Finland,1,0.00000,0.0,0.0,0.0,0.191301,...,0.0,0.000000,4.19855,0.0,2.486910,0.00000,111.7200,0.000000,0.0,0.0
4,ERR365915,Male,72,Finland,1,3.72852,0.0,0.0,0.0,0.718898,...,0.0,0.146217,1.63275,0.0,1.657120,0.00000,49.4212,0.085293,0.0,0.0

In [26]:
parkinsons_female = pd.read_csv('full_panel_condition_park_female.csv')
parkinsons_female = parkinsons_female.loc[:, ~parkinsons_female.columns.str.contains('^Unnamed')]

In [27]:
parkinsons_female.head()

,Run ID,Sex,Age,Country,Condition,Acidaminococcus,Acidovorax,Actinomyces,Adlercreutzia,Akkermansia,...,Streptococcus,Subdoligranulum,Succinatimonas,Succiniclasticum,Sutterella,Turicibacter,Unknown,Varibaculum,Veillonella,Victivallis
0,ERR365911,Female,73,Finland,Parkinsons,0.0,0.0,0.0,0.000000,0.000000,...,0.065172,1.61627,0.0,0.0,2.86757,0.000000,65.0156,0.0,0.755996,0.208551
1,ERR365913,Female,64,Finland,Parkinsons,0.0,0.0,0.0,0.000000,0.310782,...,0.167344,4.09993,0.0,0.0,0.00000,0.000000,95.6969,0.0,0.000000,0.000000
2,ERR365918,Female,73,Finland,Parkinsons,0.0,0.0,0.0,0.000000,0.000000,...,0.091408,3.40820,0.0,0.0,1.37112,0.287281,72.6822,0.0,0.000000,0.000000
3,ERR365919,Female,64,Finland,Parkinsons,0.0,0.0,0.0,0.031803,0.349836,...,0.879890,8.89431,0.0,0.0,0.00000,0.000000,55.8465,0.0,0.000000,0.000000
4,ERR365921,Female,66,Finland,Parkinsons,0.0,0.0,0.0,0.000000,0.058097,...,0.871460,5.73711,0.0,0.0,0.43573,0.000000,39.5062,0.0,0.363108,0.000000

In [28]:
parkinsons_female['Condition'] = 1
parkinsons_female.rename(columns={'Condition': 'Is Parkinsons?'}, inplace=True)

In [29]:
parkinsons_female.head()

,Run ID,Sex,Age,Country,Is Parkinsons?,Acidaminococcus,Acidovorax,Actinomyces,Adlercreutzia,Akkermansia,...,Streptococcus,Subdoligranulum,Succinatimonas,Succiniclasticum,Sutterella,Turicibacter,Unknown,Varibaculum,Veillonella,Victivallis
0,ERR365911,Female,73,Finland,1,0.0,0.0,0.0,0.000000,0.000000,...,0.065172,1.61627,0.0,0.0,2.86757,0.000000,65.0156,0.0,0.755996,0.208551
1,ERR365913,Female,64,Finland,1,0.0,0.0,0.0,0.000000,0.310782,...,0.167344,4.09993,0.0,0.0,0.00000,0.000000,95.6969,0.0,0.000000,0.000000
2,ERR365918,Female,73,Finland,1,0.0,0.0,0.0,0.000000,0.000000,...,0.091408,3.40820,0.0,0.0,1.37112,0.287281,72.6822,0.0,0.000000,0.000000
3,ERR365919,Female,64,Finland,1,0.0,0.0,0.0,0.031803,0.349836,...,0.879890,8.89431,0.0,0.0,0.00000,0.000000,55.8465,0.0,0.000000,0.000000
4,ERR365921,Female,66,Finland,1,0.0,0.0,0.0,0.000000,0.058097,...,0.871460,5.73711,0.0,0.0,0.43573,0.000000,39.5062,0.0,0.363108,0.000000

In [30]:
healthy_male.rename(columns={'Is Alzheimers?': 'Is Parkinsons?'}, inplace=True)

In [31]:
healthy_male.head()

,Run ID,Sex,Age,Country,Is Parkinsons?,BMI,Abiotrophia,Acetivibrio,Acetoanaerobium,Acetobacter,...,unclassified Clostridiales (miscellaneous),unclassified Clostridiales Family XIII. Incertae Sedis,unclassified Coriobacteriaceae,unclassified Erysipelotrichaceae (miscellaneous),unclassified Lachnospiraceae,unclassified Peptostreptococcaceae,unclassified Peptostreptococcaceae (miscellaneous),unclassified Propionibacteriaceae,unclassified Sutterellaceae,unclassified Tissierellia
0,ERR1075960,Male,0.0,United States of America,0,21.22,0.000000,0.003877,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0000,0.0,0.0,0.0,0.0000,0.0
1,ERR1854747,Male,62.0,United Kingdom,0,28.70,0.000000,0.000000,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0000,0.0,0.0,0.0,0.0000,0.0
2,ERR688529,Male,63.0,Austria,0,30.90,0.000000,0.000000,0.0,0.0,...,0.00926,0.0,0.0,0.02919,2.3641,0.0,0.0,0.0,0.0144,0.0
3,ERR1316059,Male,67.0,United States of America,0,22.15,0.000000,0.000000,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0000,0.0,0.0,0.0,0.0000,0.0
4,SRR5649200,Male,27.0,United States of America,0,20.80,0.001814,0.000000,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0000,0.0,0.0,0.0,0.0000,0.0

In [32]:
healthy_female.rename(columns={'Is Alzheimers?': 'Is Parkinsons?'}, inplace=True)

In [33]:
healthy_female.head()

,Run ID,Sex,Age,Country,Is Parkinsons?,BMI,Abiotrophia,Acanthopleuribacter,Acaryochloris,Acetoanaerobium,...,unclassified Clostridiales Family XIII. Incertae Sedis,unclassified Dermatophilaceae,unclassified Erysipelotrichaceae,unclassified Erysipelotrichaceae (miscellaneous),unclassified Lachnospiraceae,unclassified Peptostreptococcaceae,unclassified Peptostreptococcaceae (miscellaneous),unclassified Propionibacteriaceae,unclassified Ruminococcaceae,unclassified Sutterellaceae
0,ERR1842901,Female,63.0,United Kingdom,0,21.0300,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,ERR719035,Female,26.0,Canada,0,19.0311,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,SRR5648781,Female,21.0,United States of America,0,20.0000,0.001134,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ERR2032350,Female,24.0,United States of America,0,24.1300,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,ERR1089968,Female,63.0,United States of America,0,24.6300,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [34]:
is_park_df = pd.concat([parkinsons_male, parkinsons_female, healthy_male, healthy_female])

In [35]:
is_park_df.head()

,Run ID,Sex,Age,Country,Is Parkinsons?,Acidaminococcus,Adlercreutzia,Aggregatibacter,Akkermansia,Alistipes,...,Weeksella,Wigglesworthia,Wolbachia,Zooshikella,unclassified Bacteroidetes (miscellaneous),unclassified Clostridiaceae,unclassified Clostridiales,unclassified Dermatophilaceae,unclassified Erysipelotrichaceae,unclassified Ruminococcaceae
0,ERR365909,Male,61.0,Finland,1,0.00000,0.0,0.0,0.0,0.429130,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ERR365910,Male,53.0,Finland,1,0.00000,0.0,0.0,0.0,0.489687,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ERR365912,Male,66.0,Finland,1,3.34422,0.0,0.0,0.0,1.345530,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ERR365914,Male,63.0,Finland,1,0.00000,0.0,0.0,0.0,0.191301,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ERR365915,Male,72.0,Finland,1,3.72852,0.0,0.0,0.0,0.718898,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
is_park_df = is_park_df.fillna(0)

In [106]:
len(is_park_df)

239

In [37]:
is_park_df.head()

,Run ID,Sex,Age,Country,Is Parkinsons?,Acidaminococcus,Adlercreutzia,Aggregatibacter,Akkermansia,Alistipes,...,Weeksella,Wigglesworthia,Wolbachia,Zooshikella,unclassified Bacteroidetes (miscellaneous),unclassified Clostridiaceae,unclassified Clostridiales,unclassified Dermatophilaceae,unclassified Erysipelotrichaceae,unclassified Ruminococcaceae
0,ERR365909,Male,61.0,Finland,1,0.00000,0.0,0.0,0.0,0.429130,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,ERR365910,Male,53.0,Finland,1,0.00000,0.0,0.0,0.0,0.489687,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,ERR365912,Male,66.0,Finland,1,3.34422,0.0,0.0,0.0,1.345530,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ERR365914,Male,63.0,Finland,1,0.00000,0.0,0.0,0.0,0.191301,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,ERR365915,Male,72.0,Finland,1,3.72852,0.0,0.0,0.0,0.718898,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [38]:
is_park_df.to_csv('parkinsons_healthy_for_pca_one_condition.csv')

## Schizophrenia

In [39]:
sch_male = pd.read_csv('full_panel_condition_sch_male.csv')
sch_male = sch_male.loc[:, ~sch_male.columns.str.contains('^Unnamed')]

In [40]:
sch_male.head()

,Run ID,Sex,BMI,Age,Country,Condition,Abiotrophia,Acanthopleuribacter,Acetoanaerobium,Acetobacter,...,Weissella,Wenyingzhuangia,Wenzhouxiangella,Wolbachia,Xanthomonas,Xenorhabdus,Yersinia,Youngiibacter,Zoogloea,Zymomonas
0,ERR1072629,Male,17.67,64,United States of America,"Bipolar Disorder, Depression, Intestinal Disea...",0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00484,0.0
1,ERR1072937,Male,26.51,53,United States of America,"Bipolar Disorder, Cardiovascular Diseases, Dep...",0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
2,ERR1073491,Male,28.08,49,United States of America,"Bipolar Disorder, Depression, Schizophrenia",0.003157,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
3,ERR1075554,Male,30.74,62,United States of America,"Attention Deficit Disorder with Hyperactivity,...",0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
4,ERR1075686,Male,45.84,56,United States of America,"Bipolar Disorder, Depression, Lung Diseases, S...",0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0

In [41]:
sch_male['Condition'] = 1
sch_male.rename(columns={'Condition': 'Is Schizophrenia?'}, inplace=True)

In [42]:
sch_male.head()

,Run ID,Sex,BMI,Age,Country,Is Schizophrenia?,Abiotrophia,Acanthopleuribacter,Acetoanaerobium,Acetobacter,...,Weissella,Wenyingzhuangia,Wenzhouxiangella,Wolbachia,Xanthomonas,Xenorhabdus,Yersinia,Youngiibacter,Zoogloea,Zymomonas
0,ERR1072629,Male,17.67,64,United States of America,1,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00484,0.0
1,ERR1072937,Male,26.51,53,United States of America,1,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
2,ERR1073491,Male,28.08,49,United States of America,1,0.003157,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
3,ERR1075554,Male,30.74,62,United States of America,1,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
4,ERR1075686,Male,45.84,56,United States of America,1,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0

In [43]:
sch_female = pd.read_csv('full_panel_condition_sch_female.csv')
sch_female = sch_female.loc[:, ~sch_female.columns.str.contains('^Unnamed')]

In [44]:
sch_female.head()

,Run ID,Sex,BMI,Age,Country,Condition,Abiotrophia,Acanthopleuribacter,Acetivibrio,Acetoanaerobium,...,Williamsia,Wolbachia,Xanthomonas,Xenococcus,Xenorhabdus,Yersinia,Yokenella,Youngiibacter,Zoogloea,Zymomonas
0,ERR1073023,Female,34.72,35,United States of America,"Bipolar Disorder, Depression, Schizophrenia",0.0,0.005583,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
1,ERR1073394,Female,22.41,27,United States of America,"Autoimmune Diseases, Bipolar Disorder, Depress...",0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
2,ERR1073395,Female,22.41,27,United States of America,"Autoimmune Diseases, Bipolar Disorder, Depress...",0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00247,0.0
3,ERR1073490,Female,25.73,37,United States of America,"Bipolar Disorder, Depression, Schizophrenia",0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
4,ERR1073812,Female,29.71,55,United States of America,"Attention Deficit Disorder with Hyperactivity,...",0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0

In [45]:
sch_female['Condition'] = 1
sch_female.rename(columns={'Condition': 'Is Schizophrenia?'}, inplace=True)

In [46]:
sch_female.head()

,Run ID,Sex,BMI,Age,Country,Is Schizophrenia?,Abiotrophia,Acanthopleuribacter,Acetivibrio,Acetoanaerobium,...,Williamsia,Wolbachia,Xanthomonas,Xenococcus,Xenorhabdus,Yersinia,Yokenella,Youngiibacter,Zoogloea,Zymomonas
0,ERR1073023,Female,34.72,35,United States of America,1,0.0,0.005583,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
1,ERR1073394,Female,22.41,27,United States of America,1,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
2,ERR1073395,Female,22.41,27,United States of America,1,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00247,0.0
3,ERR1073490,Female,25.73,37,United States of America,1,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
4,ERR1073812,Female,29.71,55,United States of America,1,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0

In [47]:
healthy_male.rename(columns={'Is Parkinsons?': 'Is Schizophrenia?'}, inplace=True)

In [48]:
healthy_male.head()

,Run ID,Sex,Age,Country,Is Schizophrenia?,BMI,Abiotrophia,Acetivibrio,Acetoanaerobium,Acetobacter,...,unclassified Clostridiales (miscellaneous),unclassified Clostridiales Family XIII. Incertae Sedis,unclassified Coriobacteriaceae,unclassified Erysipelotrichaceae (miscellaneous),unclassified Lachnospiraceae,unclassified Peptostreptococcaceae,unclassified Peptostreptococcaceae (miscellaneous),unclassified Propionibacteriaceae,unclassified Sutterellaceae,unclassified Tissierellia
0,ERR1075960,Male,0.0,United States of America,0,21.22,0.000000,0.003877,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0000,0.0,0.0,0.0,0.0000,0.0
1,ERR1854747,Male,62.0,United Kingdom,0,28.70,0.000000,0.000000,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0000,0.0,0.0,0.0,0.0000,0.0
2,ERR688529,Male,63.0,Austria,0,30.90,0.000000,0.000000,0.0,0.0,...,0.00926,0.0,0.0,0.02919,2.3641,0.0,0.0,0.0,0.0144,0.0
3,ERR1316059,Male,67.0,United States of America,0,22.15,0.000000,0.000000,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0000,0.0,0.0,0.0,0.0000,0.0
4,SRR5649200,Male,27.0,United States of America,0,20.80,0.001814,0.000000,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0000,0.0,0.0,0.0,0.0000,0.0

In [49]:
healthy_female.rename(columns={'Is Parkinsons?': 'Is Schizophrenia?'}, inplace=True)

In [50]:
healthy_female.head()

,Run ID,Sex,Age,Country,Is Schizophrenia?,BMI,Abiotrophia,Acanthopleuribacter,Acaryochloris,Acetoanaerobium,...,unclassified Clostridiales Family XIII. Incertae Sedis,unclassified Dermatophilaceae,unclassified Erysipelotrichaceae,unclassified Erysipelotrichaceae (miscellaneous),unclassified Lachnospiraceae,unclassified Peptostreptococcaceae,unclassified Peptostreptococcaceae (miscellaneous),unclassified Propionibacteriaceae,unclassified Ruminococcaceae,unclassified Sutterellaceae
0,ERR1842901,Female,63.0,United Kingdom,0,21.0300,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,ERR719035,Female,26.0,Canada,0,19.0311,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,SRR5648781,Female,21.0,United States of America,0,20.0000,0.001134,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ERR2032350,Female,24.0,United States of America,0,24.1300,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,ERR1089968,Female,63.0,United States of America,0,24.6300,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [51]:
is_sch_df = pd.concat([sch_male, sch_female, healthy_male, healthy_female])

In [52]:
is_sch_df = is_sch_df.fillna(0)

In [53]:
is_sch_df.head()

,Run ID,Sex,BMI,Age,Country,Is Schizophrenia?,Abiotrophia,Acanthopleuribacter,Acetoanaerobium,Acetobacter,...,Tomitella,Vogesella,Weeksella,Zooshikella,unclassified Bacteroidetes (miscellaneous),unclassified Clostridiaceae,unclassified Clostridiales,unclassified Dermatophilaceae,unclassified Erysipelotrichaceae,unclassified Ruminococcaceae
0,ERR1072629,Male,17.67,64.0,United States of America,1,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,ERR1072937,Male,26.51,53.0,United States of America,1,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,ERR1073491,Male,28.08,49.0,United States of America,1,0.003157,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ERR1075554,Male,30.74,62.0,United States of America,1,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,ERR1075686,Male,45.84,56.0,United States of America,1,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [54]:
is_sch_df.to_csv('schizophrenia_healthy_for_pca_one_condition.csv')

## Epilepsy

In [55]:
ep_male = pd.read_csv('full_panel_condition_ep_male.csv')
ep_male = ep_male.loc[:, ~ep_male.columns.str.contains('^Unnamed')]

In [56]:
ep_male.head()

,Run ID,Sex,BMI,Age,Country,Condition,Abiotrophia,Acanthopleuribacter,Acetoanaerobium,Acholeplasma,...,Vibrio,Victivallis,Virgibacillus,Vulgatibacter,Weissella,Xanthomonas,Xenorhabdus,Yersinia,Zoogloea,Zymomonas
0,ERR1072832,Male,24.93,58,United States of America,Epilepsy,0.0,0.0,0.00357,0.0,...,0.0,0.003570,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
1,ERR1076844,Male,21.02,36,United States of America,"Constipation, Epilepsy, Lung Diseases, Thyroid...",0.0,0.0,0.00000,0.0,...,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
2,ERR1089831,Male,22.91,43,United States of America,Epilepsy,0.0,0.0,0.00000,0.0,...,0.0,0.005888,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
3,ERR1089867,Male,15.62,6,Canada,Epilepsy,0.0,0.0,0.00000,0.0,...,0.0,0.005153,0.0,0.0,0.010306,0.0,0.0,0.0,0.0,0.0
4,ERR1089868,Male,15.62,6,Canada,Epilepsy,0.0,0.0,0.00000,0.0,...,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0

In [57]:
ep_male['Condition'] = 1
ep_male.rename(columns={'Condition': 'Is Epilepsy?'}, inplace=True)

In [58]:
ep_male.head()

,Run ID,Sex,BMI,Age,Country,Is Epilepsy?,Abiotrophia,Acanthopleuribacter,Acetoanaerobium,Acholeplasma,...,Vibrio,Victivallis,Virgibacillus,Vulgatibacter,Weissella,Xanthomonas,Xenorhabdus,Yersinia,Zoogloea,Zymomonas
0,ERR1072832,Male,24.93,58,United States of America,1,0.0,0.0,0.00357,0.0,...,0.0,0.003570,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
1,ERR1076844,Male,21.02,36,United States of America,1,0.0,0.0,0.00000,0.0,...,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
2,ERR1089831,Male,22.91,43,United States of America,1,0.0,0.0,0.00000,0.0,...,0.0,0.005888,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
3,ERR1089867,Male,15.62,6,Canada,1,0.0,0.0,0.00000,0.0,...,0.0,0.005153,0.0,0.0,0.010306,0.0,0.0,0.0,0.0,0.0
4,ERR1089868,Male,15.62,6,Canada,1,0.0,0.0,0.00000,0.0,...,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0

In [59]:
ep_female = pd.read_csv('full_panel_condition_ep_female.csv')
ep_female = ep_female.loc[:, ~ep_female.columns.str.contains('^Unnamed')]

In [60]:
ep_female.head()

,Run ID,Sex,BMI,Age,Country,Condition,Acanthopleuribacter,Acetivibrio,Acetoanaerobium,Acetobacterium,...,Wandonia,Weeksella,Weissella,Wenzhouxiangella,Wolbachia,Xanthomonas,Xenorhabdus,Yersinia,Youngiibacter,Zoogloea
0,ERR1073812,Female,29.71,55,United States of America,"Attention Deficit Disorder with Hyperactivity,...",0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0
1,ERR1090471,Female,38.01,47,United States of America,"Autoimmune Diseases, Bipolar Disorder, Constip...",0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.00000,0.000000,0.000000,0.0,0.004069,0.000000,0.0,0.0
2,ERR1091746,Female,31.09,59,United States of America,"Autoimmune Diseases, Diabetes Mellitus, Epilep...",0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.00000,0.000000,0.000000,0.0,0.001851,0.005553,0.0,0.0
3,ERR1091758,Female,21.79,62,United States of America,"Attention Deficit Disorder with Hyperactivity,...",0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.00000,0.000000,0.000000,0.0,0.000000,0.002317,0.0,0.0
4,ERR1160392,Female,35.19,50,United States of America,"Bipolar Disorder, Constipation, Depression, Ep...",0.0,0.0,0.001275,0.001275,...,0.0,0.0,0.00255,0.001275,0.001275,0.0,0.001275,0.005101,0.0,0.0

In [61]:
ep_female['Condition'] = 1
ep_female.rename(columns={'Condition': 'Is Epilepsy?'}, inplace=True)

In [62]:
ep_female.head()

,Run ID,Sex,BMI,Age,Country,Is Epilepsy?,Acanthopleuribacter,Acetivibrio,Acetoanaerobium,Acetobacterium,...,Wandonia,Weeksella,Weissella,Wenzhouxiangella,Wolbachia,Xanthomonas,Xenorhabdus,Yersinia,Youngiibacter,Zoogloea
0,ERR1073812,Female,29.71,55,United States of America,1,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0
1,ERR1090471,Female,38.01,47,United States of America,1,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.00000,0.000000,0.000000,0.0,0.004069,0.000000,0.0,0.0
2,ERR1091746,Female,31.09,59,United States of America,1,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.00000,0.000000,0.000000,0.0,0.001851,0.005553,0.0,0.0
3,ERR1091758,Female,21.79,62,United States of America,1,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.00000,0.000000,0.000000,0.0,0.000000,0.002317,0.0,0.0
4,ERR1160392,Female,35.19,50,United States of America,1,0.0,0.0,0.001275,0.001275,...,0.0,0.0,0.00255,0.001275,0.001275,0.0,0.001275,0.005101,0.0,0.0

In [63]:
healthy_male.rename(columns={'Is Schizophrenia?': 'Is Epilepsy?'}, inplace=True)

In [64]:
healthy_male.head()

,Run ID,Sex,Age,Country,Is Epilepsy?,BMI,Abiotrophia,Acetivibrio,Acetoanaerobium,Acetobacter,...,unclassified Clostridiales (miscellaneous),unclassified Clostridiales Family XIII. Incertae Sedis,unclassified Coriobacteriaceae,unclassified Erysipelotrichaceae (miscellaneous),unclassified Lachnospiraceae,unclassified Peptostreptococcaceae,unclassified Peptostreptococcaceae (miscellaneous),unclassified Propionibacteriaceae,unclassified Sutterellaceae,unclassified Tissierellia
0,ERR1075960,Male,0.0,United States of America,0,21.22,0.000000,0.003877,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0000,0.0,0.0,0.0,0.0000,0.0
1,ERR1854747,Male,62.0,United Kingdom,0,28.70,0.000000,0.000000,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0000,0.0,0.0,0.0,0.0000,0.0
2,ERR688529,Male,63.0,Austria,0,30.90,0.000000,0.000000,0.0,0.0,...,0.00926,0.0,0.0,0.02919,2.3641,0.0,0.0,0.0,0.0144,0.0
3,ERR1316059,Male,67.0,United States of America,0,22.15,0.000000,0.000000,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0000,0.0,0.0,0.0,0.0000,0.0
4,SRR5649200,Male,27.0,United States of America,0,20.80,0.001814,0.000000,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0000,0.0,0.0,0.0,0.0000,0.0

In [65]:
healthy_female.rename(columns={'Is Schizophrenia?': 'Is Epilepsy?'}, inplace=True)

In [66]:
healthy_female.head()

,Run ID,Sex,Age,Country,Is Epilepsy?,BMI,Abiotrophia,Acanthopleuribacter,Acaryochloris,Acetoanaerobium,...,unclassified Clostridiales Family XIII. Incertae Sedis,unclassified Dermatophilaceae,unclassified Erysipelotrichaceae,unclassified Erysipelotrichaceae (miscellaneous),unclassified Lachnospiraceae,unclassified Peptostreptococcaceae,unclassified Peptostreptococcaceae (miscellaneous),unclassified Propionibacteriaceae,unclassified Ruminococcaceae,unclassified Sutterellaceae
0,ERR1842901,Female,63.0,United Kingdom,0,21.0300,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,ERR719035,Female,26.0,Canada,0,19.0311,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,SRR5648781,Female,21.0,United States of America,0,20.0000,0.001134,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ERR2032350,Female,24.0,United States of America,0,24.1300,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,ERR1089968,Female,63.0,United States of America,0,24.6300,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [67]:
is_ep_df = pd.concat([ep_male, ep_female, healthy_male, healthy_female])

In [68]:
is_ep_df = is_ep_df.fillna(0)

In [69]:
is_ep_df.head()

,Run ID,Sex,BMI,Age,Country,Is Epilepsy?,Abiotrophia,Acanthopleuribacter,Acetoanaerobium,Acholeplasma,...,Turicella,Vogesella,Wigglesworthia,Zooshikella,unclassified Bacteroidetes (miscellaneous),unclassified Clostridiaceae,unclassified Clostridiales,unclassified Dermatophilaceae,unclassified Erysipelotrichaceae,unclassified Ruminococcaceae
0,ERR1072832,Male,24.93,58.0,United States of America,1,0.0,0.0,0.00357,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,ERR1076844,Male,21.02,36.0,United States of America,1,0.0,0.0,0.00000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,ERR1089831,Male,22.91,43.0,United States of America,1,0.0,0.0,0.00000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ERR1089867,Male,15.62,6.0,Canada,1,0.0,0.0,0.00000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,ERR1089868,Male,15.62,6.0,Canada,1,0.0,0.0,0.00000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [70]:
len(is_ep_df)

207

In [71]:
is_ep_df.to_csv('epilepsy_healthy_for_pca_one_condition.csv')

## Bipolar

In [72]:
bi_male = pd.read_csv('full_panel_condition_bi_male.csv')
bi_male = bi_male.loc[:, ~bi_male.columns.str.contains('^Unnamed')]

In [73]:
bi_male.head()

,Run ID,Sex,BMI,Age,Country,Condition,Abiotrophia,Acanthopleuribacter,Acetivibrio,Acetoanaerobium,...,Weissella,Wenyingzhuangia,Wenzhouxiangella,Wolbachia,Xanthomonas,Xenorhabdus,Yersinia,Youngiibacter,Zoogloea,Zymomonas
0,ERR1072629,Male,17.67,64,United States of America,"Bipolar Disorder, Depression, Intestinal Disea...",0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00484,0.0
1,ERR1072937,Male,26.51,53,United States of America,"Bipolar Disorder, Cardiovascular Diseases, Dep...",0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
2,ERR1073491,Male,28.08,49,United States of America,"Bipolar Disorder, Depression, Schizophrenia",0.003157,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
3,ERR1075554,Male,30.74,62,United States of America,"Attention Deficit Disorder with Hyperactivity,...",0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
4,ERR1075686,Male,45.84,56,United States of America,"Bipolar Disorder, Depression, Lung Diseases, S...",0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0

In [74]:
bi_male['Condition'] = 1
bi_male.rename(columns={'Condition': 'Is Bipolar?'}, inplace=True)

In [75]:
bi_male.head()

,Run ID,Sex,BMI,Age,Country,Is Bipolar?,Abiotrophia,Acanthopleuribacter,Acetivibrio,Acetoanaerobium,...,Weissella,Wenyingzhuangia,Wenzhouxiangella,Wolbachia,Xanthomonas,Xenorhabdus,Yersinia,Youngiibacter,Zoogloea,Zymomonas
0,ERR1072629,Male,17.67,64,United States of America,1,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00484,0.0
1,ERR1072937,Male,26.51,53,United States of America,1,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
2,ERR1073491,Male,28.08,49,United States of America,1,0.003157,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
3,ERR1075554,Male,30.74,62,United States of America,1,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
4,ERR1075686,Male,45.84,56,United States of America,1,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0

In [76]:
bi_female = pd.read_csv('full_panel_condition_bi_female.csv')
bi_female = bi_female.loc[:, ~bi_female.columns.str.contains('^Unnamed')]

In [77]:
bi_female.head()

,Run ID,Sex,BMI,Age,Country,Condition,Abiotrophia,Acanthopleuribacter,Acetivibrio,Acetoanaerobium,...,Williamsia,Wolbachia,Xanthomonas,Xenococcus,Xenorhabdus,Yersinia,Yokenella,Youngiibacter,Zoogloea,Zymomonas
0,ERR1073023,Female,34.72,35,United States of America,"Bipolar Disorder, Depression, Schizophrenia",0.0,0.005583,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
1,ERR1073394,Female,22.41,27,United States of America,"Autoimmune Diseases, Bipolar Disorder, Depress...",0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
2,ERR1073395,Female,22.41,27,United States of America,"Autoimmune Diseases, Bipolar Disorder, Depress...",0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00247,0.0
3,ERR1073490,Female,25.73,37,United States of America,"Bipolar Disorder, Depression, Schizophrenia",0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
4,ERR1073812,Female,29.71,55,United States of America,"Attention Deficit Disorder with Hyperactivity,...",0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0

In [78]:
bi_female['Condition'] = 1
bi_female.rename(columns={'Condition': 'Is Bipolar?'}, inplace=True)

In [79]:
bi_female.head()

,Run ID,Sex,BMI,Age,Country,Is Bipolar?,Abiotrophia,Acanthopleuribacter,Acetivibrio,Acetoanaerobium,...,Williamsia,Wolbachia,Xanthomonas,Xenococcus,Xenorhabdus,Yersinia,Yokenella,Youngiibacter,Zoogloea,Zymomonas
0,ERR1073023,Female,34.72,35,United States of America,1,0.0,0.005583,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
1,ERR1073394,Female,22.41,27,United States of America,1,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
2,ERR1073395,Female,22.41,27,United States of America,1,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00247,0.0
3,ERR1073490,Female,25.73,37,United States of America,1,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
4,ERR1073812,Female,29.71,55,United States of America,1,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0

In [80]:
healthy_male.rename(columns={'Is Epilepsy?': 'Is Bipolar?'}, inplace=True)

In [81]:
healthy_male.head()

,Run ID,Sex,Age,Country,Is Bipolar?,BMI,Abiotrophia,Acetivibrio,Acetoanaerobium,Acetobacter,...,unclassified Clostridiales (miscellaneous),unclassified Clostridiales Family XIII. Incertae Sedis,unclassified Coriobacteriaceae,unclassified Erysipelotrichaceae (miscellaneous),unclassified Lachnospiraceae,unclassified Peptostreptococcaceae,unclassified Peptostreptococcaceae (miscellaneous),unclassified Propionibacteriaceae,unclassified Sutterellaceae,unclassified Tissierellia
0,ERR1075960,Male,0.0,United States of America,0,21.22,0.000000,0.003877,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0000,0.0,0.0,0.0,0.0000,0.0
1,ERR1854747,Male,62.0,United Kingdom,0,28.70,0.000000,0.000000,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0000,0.0,0.0,0.0,0.0000,0.0
2,ERR688529,Male,63.0,Austria,0,30.90,0.000000,0.000000,0.0,0.0,...,0.00926,0.0,0.0,0.02919,2.3641,0.0,0.0,0.0,0.0144,0.0
3,ERR1316059,Male,67.0,United States of America,0,22.15,0.000000,0.000000,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0000,0.0,0.0,0.0,0.0000,0.0
4,SRR5649200,Male,27.0,United States of America,0,20.80,0.001814,0.000000,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0000,0.0,0.0,0.0,0.0000,0.0

In [82]:
healthy_female.rename(columns={'Is Epilepsy?': 'Is Bipolar?'}, inplace=True)

In [83]:
healthy_female.head()

,Run ID,Sex,Age,Country,Is Bipolar?,BMI,Abiotrophia,Acanthopleuribacter,Acaryochloris,Acetoanaerobium,...,unclassified Clostridiales Family XIII. Incertae Sedis,unclassified Dermatophilaceae,unclassified Erysipelotrichaceae,unclassified Erysipelotrichaceae (miscellaneous),unclassified Lachnospiraceae,unclassified Peptostreptococcaceae,unclassified Peptostreptococcaceae (miscellaneous),unclassified Propionibacteriaceae,unclassified Ruminococcaceae,unclassified Sutterellaceae
0,ERR1842901,Female,63.0,United Kingdom,0,21.0300,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,ERR719035,Female,26.0,Canada,0,19.0311,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,SRR5648781,Female,21.0,United States of America,0,20.0000,0.001134,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ERR2032350,Female,24.0,United States of America,0,24.1300,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,ERR1089968,Female,63.0,United States of America,0,24.6300,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [84]:
is_bi_df = pd.concat([bi_male, bi_female, healthy_male, healthy_female])

In [85]:
is_bi_df = is_bi_df.fillna(0)

In [86]:
is_bi_df.head()

,Run ID,Sex,BMI,Age,Country,Is Bipolar?,Abiotrophia,Acanthopleuribacter,Acetivibrio,Acetoanaerobium,...,Tomitella,Vogesella,Weeksella,Zooshikella,unclassified Bacteroidetes (miscellaneous),unclassified Clostridiaceae,unclassified Clostridiales,unclassified Dermatophilaceae,unclassified Erysipelotrichaceae,unclassified Ruminococcaceae
0,ERR1072629,Male,17.67,64.0,United States of America,1,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,ERR1072937,Male,26.51,53.0,United States of America,1,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,ERR1073491,Male,28.08,49.0,United States of America,1,0.003157,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ERR1075554,Male,30.74,62.0,United States of America,1,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,ERR1075686,Male,45.84,56.0,United States of America,1,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [87]:
len(is_bi_df)

604

In [88]:
is_bi_df.to_csv('bipolar_healthy_for_pca_one_condition.csv')

## Depression

In [89]:
dep_male = pd.read_csv('full_panel_condition_dep_male.csv')
dep_male = dep_male.loc[:, ~dep_male.columns.str.contains('^Unnamed')]

In [90]:
dep_male.head()

,Run ID,Sex,BMI,Age,Country,Condition,Abiotrophia,Acanthopleuribacter,Acetoanaerobium,Acetobacter,...,Weissella,Wenyingzhuangia,Wenzhouxiangella,Wolbachia,Xanthomonas,Xenorhabdus,Yersinia,Youngiibacter,Zoogloea,Zymomonas
0,ERR1072629,Male,17.67,64.0,United States of America,"Bipolar Disorder, Depression, Intestinal Disea...",0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00484,0.0
1,ERR1072937,Male,26.51,53.0,United States of America,"Bipolar Disorder, Cardiovascular Diseases, Dep...",0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
2,ERR1073491,Male,28.08,49.0,United States of America,"Bipolar Disorder, Depression, Schizophrenia",0.003157,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
3,ERR1075554,Male,30.74,62.0,United States of America,"Attention Deficit Disorder with Hyperactivity,...",0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
4,ERR1075686,Male,45.84,56.0,United States of America,"Bipolar Disorder, Depression, Lung Diseases, S...",0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0

In [91]:
dep_male['Condition'] = 1
dep_male.rename(columns={'Condition': 'Is Depression?'}, inplace=True)

In [92]:
dep_male.head()

,Run ID,Sex,BMI,Age,Country,Is Depression?,Abiotrophia,Acanthopleuribacter,Acetoanaerobium,Acetobacter,...,Weissella,Wenyingzhuangia,Wenzhouxiangella,Wolbachia,Xanthomonas,Xenorhabdus,Yersinia,Youngiibacter,Zoogloea,Zymomonas
0,ERR1072629,Male,17.67,64.0,United States of America,1,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00484,0.0
1,ERR1072937,Male,26.51,53.0,United States of America,1,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
2,ERR1073491,Male,28.08,49.0,United States of America,1,0.003157,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
3,ERR1075554,Male,30.74,62.0,United States of America,1,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
4,ERR1075686,Male,45.84,56.0,United States of America,1,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0

In [93]:
dep_female = pd.read_csv('full_panel_condition_dep_female.csv')
dep_female = dep_female.loc[:, ~dep_female.columns.str.contains('^Unnamed')]

In [94]:
dep_female.head()

,Run ID,Sex,BMI,Age,Country,Condition,Abiotrophia,Acanthopleuribacter,Acetivibrio,Acetoanaerobium,...,Williamsia,Wolbachia,Xanthomonas,Xenococcus,Xenorhabdus,Yersinia,Yokenella,Youngiibacter,Zoogloea,Zymomonas
0,ERR1073023,Female,34.72,35,United States of America,"Bipolar Disorder, Depression, Schizophrenia",0.0,0.005583,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
1,ERR1073394,Female,22.41,27,United States of America,"Autoimmune Diseases, Bipolar Disorder, Depress...",0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
2,ERR1073395,Female,22.41,27,United States of America,"Autoimmune Diseases, Bipolar Disorder, Depress...",0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00247,0.0
3,ERR1073490,Female,25.73,37,United States of America,"Bipolar Disorder, Depression, Schizophrenia",0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
4,ERR1073812,Female,29.71,55,United States of America,"Attention Deficit Disorder with Hyperactivity,...",0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0

In [95]:
dep_female['Condition'] = 1
dep_female.rename(columns={'Condition': 'Is Depression?'}, inplace=True)

In [96]:
dep_female.head()

,Run ID,Sex,BMI,Age,Country,Is Depression?,Abiotrophia,Acanthopleuribacter,Acetivibrio,Acetoanaerobium,...,Williamsia,Wolbachia,Xanthomonas,Xenococcus,Xenorhabdus,Yersinia,Yokenella,Youngiibacter,Zoogloea,Zymomonas
0,ERR1073023,Female,34.72,35,United States of America,1,0.0,0.005583,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
1,ERR1073394,Female,22.41,27,United States of America,1,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
2,ERR1073395,Female,22.41,27,United States of America,1,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00247,0.0
3,ERR1073490,Female,25.73,37,United States of America,1,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
4,ERR1073812,Female,29.71,55,United States of America,1,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0

In [97]:
healthy_male.rename(columns={'Is Bipolar?': 'Is Depression?'}, inplace=True)

In [98]:
healthy_male.head()

,Run ID,Sex,Age,Country,Is Depression?,BMI,Abiotrophia,Acetivibrio,Acetoanaerobium,Acetobacter,...,unclassified Clostridiales (miscellaneous),unclassified Clostridiales Family XIII. Incertae Sedis,unclassified Coriobacteriaceae,unclassified Erysipelotrichaceae (miscellaneous),unclassified Lachnospiraceae,unclassified Peptostreptococcaceae,unclassified Peptostreptococcaceae (miscellaneous),unclassified Propionibacteriaceae,unclassified Sutterellaceae,unclassified Tissierellia
0,ERR1075960,Male,0.0,United States of America,0,21.22,0.000000,0.003877,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0000,0.0,0.0,0.0,0.0000,0.0
1,ERR1854747,Male,62.0,United Kingdom,0,28.70,0.000000,0.000000,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0000,0.0,0.0,0.0,0.0000,0.0
2,ERR688529,Male,63.0,Austria,0,30.90,0.000000,0.000000,0.0,0.0,...,0.00926,0.0,0.0,0.02919,2.3641,0.0,0.0,0.0,0.0144,0.0
3,ERR1316059,Male,67.0,United States of America,0,22.15,0.000000,0.000000,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0000,0.0,0.0,0.0,0.0000,0.0
4,SRR5649200,Male,27.0,United States of America,0,20.80,0.001814,0.000000,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0000,0.0,0.0,0.0,0.0000,0.0

In [99]:
healthy_female.rename(columns={'Is Bipolar?': 'Is Depression?'}, inplace=True)

In [100]:
healthy_female.head()

,Run ID,Sex,Age,Country,Is Depression?,BMI,Abiotrophia,Acanthopleuribacter,Acaryochloris,Acetoanaerobium,...,unclassified Clostridiales Family XIII. Incertae Sedis,unclassified Dermatophilaceae,unclassified Erysipelotrichaceae,unclassified Erysipelotrichaceae (miscellaneous),unclassified Lachnospiraceae,unclassified Peptostreptococcaceae,unclassified Peptostreptococcaceae (miscellaneous),unclassified Propionibacteriaceae,unclassified Ruminococcaceae,unclassified Sutterellaceae
0,ERR1842901,Female,63.0,United Kingdom,0,21.0300,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,ERR719035,Female,26.0,Canada,0,19.0311,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,SRR5648781,Female,21.0,United States of America,0,20.0000,0.001134,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ERR2032350,Female,24.0,United States of America,0,24.1300,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,ERR1089968,Female,63.0,United States of America,0,24.6300,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [101]:
is_dep_df = pd.concat([dep_male, dep_female, healthy_male, healthy_female])

In [102]:
is_dep_df = is_dep_df.fillna(0)

In [103]:
is_dep_df.head()

,Run ID,Sex,BMI,Age,Country,Is Depression?,Abiotrophia,Acanthopleuribacter,Acetoanaerobium,Acetobacter,...,Tomitella,Vogesella,Weeksella,Zooshikella,unclassified Bacteroidetes (miscellaneous),unclassified Clostridiaceae,unclassified Clostridiales,unclassified Dermatophilaceae,unclassified Erysipelotrichaceae,unclassified Ruminococcaceae
0,ERR1072629,Male,17.67,64.0,United States of America,1,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,ERR1072937,Male,26.51,53.0,United States of America,1,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,ERR1073491,Male,28.08,49.0,United States of America,1,0.003157,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ERR1075554,Male,30.74,62.0,United States of America,1,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,ERR1075686,Male,45.84,56.0,United States of America,1,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [104]:
len(is_dep_df)

513

In [105]:
is_dep_df.to_csv('depression_healthy_for_pca_one_condition.csv')